create user PROYECTOFINAL identified by usuario;
grant connect to PROYECTOFINAL;
grant resource to PROYECTOFINAL;
grant unlimited tablespace to PROYECTOFINAL;
disconnect
connect PROYECTOFINAL/usuario;

--CREACIÓN DE TABLAS
CREATE TABLE ALUMNO (
DNI VARCHAR2(9),
NOMBRE VARCHAR2(40),
APELLIDO1 VARCHAR2(45),
APELLIDO2 VARCHAR2(45),
FECHA_NACIMIENTO DATE,
TELEFONO VARCHAR2(12) UNIQUE,
DIRECCION VARCHAR2(50),
CONSTRAINT PK_ALUMNO PRIMARY KEY (DNI)
);

CREATE TABLE EXAMEN (
FECHA_EXAMEN DATE,
DNI_ALUMNO VARCHAR2(9),
TIPO_EXAMEN VARCHAR2(40)
	CHECK ( TIPO_EXAMEN IN ('Teórico', 'Práctico') ),
NOTA NUMBER(3,1),
CONSTRAINT FK_EXAMEN FOREIGN KEY (DNI_ALUMNO) REFERENCES ALUMNO (DNI),
CONSTRAINT PK_EXAMEN PRIMARY KEY (FECHA_EXAMEN, DNI_ALUMNO)
);

CREATE TABLE PROFESOR (
DNI VARCHAR2(9),
NOMBRE VARCHAR2(40),
APELLIDO1 VARCHAR2(45),
APELLIDO2 VARCHAR2(45),
FECHA_NACIMIENTO DATE,
SALARIO NUMBER(6,2) NOT NULL,
TELEFONO VARCHAR2(12),
CONSTRAINT PK_PROFESOR PRIMARY KEY (DNI)
);

CREATE TABLE COCHE (
MATRICULA VARCHAR2(8),
MARCA VARCHAR2(40),
MODELO VARCHAR2(40),
FECHA_COMPRA DATE,
COLOR VARCHAR2(35),
COMBUSTIBLE VARCHAR2(35) DEFAULT 'Gasolina',
NUM_BASTIDOR VARCHAR2(17) UNIQUE NOT NULL,
CONSTRAINT PK_COCHE PRIMARY KEY (MATRICULA)
);

CREATE TABLE CONDUCE (
MATRICULA VARCHAR2(8),
DNI_ALUMNO VARCHAR2(9),
DNI_PROFESOR VARCHAR2(9),
FECHA_PRACTICA DATE,
CONSTRAINT FK_CONDUCE1 FOREIGN KEY (MATRICULA) REFERENCES COCHE (MATRICULA),
CONSTRAINT FK_CONDUCE2 FOREIGN KEY (DNI_ALUMNO) REFERENCES ALUMNO (DNI),
CONSTRAINT FK_CONDUCE3 FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESOR (DNI),
CONSTRAINT PK_CONDUCE PRIMARY KEY (MATRICULA, DNI_ALUMNO, DNI_PROFESOR, FECHA_PRACTICA)
);
--RESTRICCIONES

--1
ALTER TABLE ALUMNO ADD CONSTRAINT CK_DNI_ALUMNO CHECK (REGEXP_LIKE(DNI,'[0-9]{8}[A-Z]'));
ALTER TABLE PROFESOR ADD CONSTRAINT CK_DNI_PROFESOR CHECK (REGEXP_LIKE(DNI,'[0-9]{8}[A-Z]'));

--2
ALTER TABLE ALUMNO ADD CONSTRAINT CK_MAYOR_EDAD CHECK ((2022 - TO_CHAR(FECHA_NACIMIENTO,'YYYY')) >= 18);

--3
ALTER TABLE PROFESOR ADD CONSTRAINT CK_SAL_SMI CHECK (SALARIO >= 1166.7);

--4
ALTER TABLE COCHE ADD CONSTRAINT CK_FECHA_COMPRA CHECK ((2022 - TO_CHAR(FECHA_COMPRA,'YYYY')) < 5);

--consultas

--1
SELECT NOMBRE||', '||APELLIDO1||' '||APELLIDO2 FROM ALUMNO WHERE TO_CHAR(SYSDATE,'YYYY') - TO_CHAR(FECHA_NACIMIENTO,'YYYY') > 30;

--2
CREATE VIEW VIEW_PROFES (NOMBRE_Y_SALARIO) AS SELECT NOMBRE||', '||APELLIDO1||' '||APELLIDO2||' y cobra: '||SALARIO FROM PROFESOR;

--3
SELECT NOMBRE||', '||APELLIDO1||' '||APELLIDO2||' vive en:  '||DIRECCION FROM ALUMNO WHERE DNI IN (SELECT DNI_ALUMNO FROM EXAMEN WHERE TIPO_EXAMEN='Teórico');

--4
SELECT NOMBRE||' '||APELLIDO1||', '||FECHA_PRACTICA FROM ALUMNO A, CONDUCE C WHERE A.DNI=C.DNI_ALUMNO;

--5
INSERT INTO COCHE (MATRICULA, MARCA, MODELO, FECHA_COMPRA, COLOR, NUM_BASTIDOR) SELECT '7895LTC', MARCA, MODELO, FECHA_COMPRA, COLOR, '1GCGF25V349156534' FROM COCHE WHERE NUM_BASTIDOR='1GCGF25V349156533';

--6
UPDATE PROFESOR SET SALARIO = (SELECT SALARIO *1.35 FROM PROFESOR WHERE FECHA_NACIMIENTO=(SELECT MIN(FECHA_NACIMIENTO) FROM PROFESOR)) WHERE FECHA_NACIMIENTO = (SELECT MIN(FECHA_NACIMIENTO) FROM PROFESOR);

--7
DELETE FROM COCHE WHERE MATRICULA ='7895LTC';

--8
SELECT NOMBRE||', '||APELLIDO1||' '||APELLIDO2||' HA DADO '||COUNT(*) ||' CLASES' FROM ALUMNO A, CONDUCE C WHERE A.DNI=C.DNI_ALUMNO GROUP BY NOMBRE, APELLIDO1, APELLIDO2 HAVING COUNT(*) > 5;

--9
SELECT NOMBRE||' '||APELLIDO1||' '||coalesce(to_char(FECHA_PRACTICA), 'No tiene practicas') FROM ALUMNO A, CONDUCE C WHERE A.DNI=C.DNI_ALUMNO(+);

--10
SELECT DNI FROM ALUMNO MINUS SELECT DNI_ALUMNO FROM CONDUCE;

--11
SELECT NOMBRE||' '||APELLIDO1 FROM ALUMNO WHERE DNI IN (SELECT DNI_ALUMNO FROM CONDUCE WHERE DNI_PROFESOR= (SELECT DNI PROFESOR WHERE NOMBRE='Manuel' AND APELLIDO1='García' AND APELLIDO2='Gálvez'));

--12
create view vista_profe_coches ("Profesores en coches Gasolina") as select nombre||' '||apellido1||' '||apellido2||' ha impartido '||count(*)||' clases' from profesor p, conduce c where p.dni=c.dni_profesor and dni IN (select dni_profesor from conduce where matricula in (select matricula from coche where combustible='Gasolina')) group by nombre, apellido1, apellido2 order by count(*) desc ;

