CREATE TABLE ALUMNO (
DNI VARCHAR(9),
NOMBRE VARCHAR(40),
APELLIDO1 VARCHAR(45),
APELLIDO2 VARCHAR(45),
FECHA_NACIMIENTO DATETIME,
TELEFONO VARCHAR(12) UNIQUE,
DIRECCION VARCHAR(50),
CONSTRAINT PK_ALUMNO PRIMARY KEY (DNI)
);

CREATE TABLE EXAMEN (
FECHA_EXAMEN DATETIME,
DNI_ALUMNO VARCHAR(9),
TIPO_EXAMEN VARCHAR(40)
	CHECK ( TIPO_EXAMEN IN ('Teórico', 'Práctico') ),
NOTA DECIMAL(3,1),
CONSTRAINT FK_EXAMEN FOREIGN KEY (DNI_ALUMNO) REFERENCES ALUMNO (DNI),
CONSTRAINT PK_EXAMEN PRIMARY KEY (FECHA_EXAMEN, DNI_ALUMNO)
);

CREATE TABLE PROFESOR (
DNI VARCHAR(9),
NOMBRE VARCHAR(40),
APELLIDO1 VARCHAR(45),
APELLIDO2 VARCHAR(45),
FECHA_NACIMIENTO DATETIME,
SALARIO DECIMAL(6,2) NOT NULL,
TELEFONO VARCHAR(12),
CONSTRAINT PK_PROFESOR PRIMARY KEY (DNI)
);

CREATE TABLE COCHE (
MATRICULA VARCHAR(8),
MARCA VARCHAR(40),
MODELO VARCHAR(40),
FECHA_COMPRA DATETIME,
COLOR VARCHAR(35),
COMBUSTIBLE VARCHAR(35) DEFAULT 'Gasolina',
NUM_BASTIDOR VARCHAR(17) UNIQUE NOT NULL,
CONSTRAINT PK_COCHE PRIMARY KEY (MATRICULA)
);

CREATE TABLE CONDUCE (
MATRICULA VARCHAR(8),
DNI_ALUMNO VARCHAR(9),
DNI_PROFESOR VARCHAR(9),
FECHA_PRACTICA DATETIME,
CONSTRAINT FK_CONDUCE1 FOREIGN KEY (MATRICULA) REFERENCES COCHE (MATRICULA),
CONSTRAINT FK_CONDUCE2 FOREIGN KEY (DNI_ALUMNO) REFERENCES ALUMNO (DNI),
CONSTRAINT FK_CONDUCE3 FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESOR (DNI),
CONSTRAINT PK_CONDUCE PRIMARY KEY (MATRICULA, DNI_ALUMNO, DNI_PROFESOR, FECHA_PRACTICA)
);

--RESTRICCIONES
--1
ALTER TABLE ALUMNO ADD CONSTRAINT CK_DNI_ALUMNO CHECK (DNI REGEXP '[0-9]{8}[A-Z]');
ALTER TABLE PROFESOR ADD CONSTRAINT CK_DNI_PROFESOR CHECK (DNI REGEXP '[0-9]{8}[A-Z]');
--2
ALTER TABLE ALUMNO ADD CONSTRAINT CK_MAYOR_EDAD CHECK ((2022 - YEAR(FECHA_NACIMIENTO)) >= 18);
--3
ALTER TABLE PROFESOR ADD CONSTRAINT CK_SAL_SMI CHECK (SALARIO >= 1166.7);
--4
ALTER TABLE COCHE ADD CONSTRAINT CK_FECHA_COMPRA CHECK ((2022 - YEAR(FECHA_COMPRA)) < 5);

--consultas
--1
SELECT CONCAT(IFNULL(NOMBRE, ''),', ',IFNULL(APELLIDO1, ''),' ', IFNULL(APELLIDO2, '')) FROM ALUMNO WHERE DATE_FORMAT(SYSDATE(),'%Y') - DATE_FORMAT(FECHA_NACIMIENTO,'%Y') > 30;

--2
CREATE VIEW VIEW_PROFES (NOMBRE_Y_SALARIO) AS SELECT CONCAT(IFNULL(NOMBRE, ''),', ',IFNULL(APELLIDO1, ''),' ',IFNULL(APELLIDO2, ''),' y cobra: ',IFNULL(SALARIO, '')) FROM PROFESOR;

--3
SELECT CONCAT(IFNULL(NOMBRE, ''),', ',IFNULL(APELLIDO1, ''),' ',IFNULL(APELLIDO2, ''),' vive en:  ',IFNULL(DIRECCION, '')) FROM ALUMNO WHERE DNI IN (SELECT DNI_ALUMNO FROM EXAMEN WHERE TIPO_EXAMEN='Teórico');

--4
SELECT CONCAT(IFNULL(NOMBRE, ''),' ',IFNULL(APELLIDO1, ''),', ',IFNULL(FECHA_PRACTICA, '')) FROM ALUMNO A, CONDUCE C WHERE A.DNI=C.DNI_ALUMNO;

--5
INSERT INTO COCHE (MATRICULA, MARCA, MODELO, FECHA_COMPRA, COLOR, NUM_BASTIDOR) SELECT '7895LTC', MARCA, MODELO, FECHA_COMPRA, COLOR, '1GCGF25V349156534' FROM COCHE WHERE NUM_BASTIDOR='1GCGF25V349156533';

--6
UPDATE PROFESOR SET SALARIO = (SELECT SALARIO *1.35 FROM PROFESOR WHERE FECHA_NACIMIENTO=(SELECT MIN(FECHA_NACIMIENTO) FROM PROFESOR)) WHERE FECHA_NACIMIENTO = (SELECT MIN(FECHA_NACIMIENTO) FROM PROFESOR);

--7
DELETE FROM COCHE WHERE MATRICULA ='7895LTC';

--8
SELECT CONCAT(IFNULL(NOMBRE, ''),', ',IFNULL(APELLIDO1, ''),' ',IFNULL(APELLIDO2, ''),' HA DADO ',IFNULL(COUNT(*), '') ,' CLASES') FROM ALUMNO A, CONDUCE C WHERE A.DNI=C.DNI_ALUMNO GROUP BY NOMBRE, APELLIDO1, APELLIDO2 HAVING COUNT(*) > 5;

--9
SELECT CONCAT(IFNULL(NOMBRE, ''),' ',IFNULL(APELLIDO1, ''),' ',ifnull(coalesce(FECHA_PRACTICA, 'No tiene practicas'), '')) FROM ALUMNO A LEFT OUTER JOIN CONDUCE C ON A.DNI=C.DNI_ALUMNO;

--10
(SELECT DNI FROM ALUMNO) EXCEPT (SELECT DNI_ALUMNO FROM CONDUCE);

--11
SELECT CONCAT(IFNULL(NOMBRE, ''),' ',IFNULL(APELLIDO1, '')) FROM ALUMNO WHERE DNI IN (SELECT DNI_ALUMNO FROM CONDUCE WHERE DNI_PROFESOR= (SELECT DNI PROFESOR WHERE NOMBRE='Manuel' APELLIDO1='García' APELLIDO2='Gálvez'));

--12
create view vista_profe_coches (`Profesores en coches Gasolina`) as select concat(ifnull(nombre, ''),' ',ifnull(apellido1, ''),' ',ifnull(apellido2, ''),' ha impartido ',ifnull(count(*), ''),' clases') from PROFESOR p, CONDUCE c where
p.dni=c.dni_profesor and dni IN (select dni_profesor from CONDUCE where matricula in (select matricula from COCHE where combustible='Gasolina')) group by nombre, apellido1, apellido2 order by count(*) desc ;
